# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            dshoemaker
tagline:          ' '
description:      'Kansas City based Software Engineer. Currently drinking coffee and working in Rails'
url:              http://dshoemaker.github.io
baseurl:          /

author:
  name:           'Drew Shoemaker'
  url:            http://dshoemaker.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dshoemaker/dshoemaker.github.io
